sudo: false
language: node_js
node_js:
- '7'
install:
- bin/installDeps.sh
- export GIT_HASH=$(git rev-parse --verify --short HEAD)
- 'echo "web: bin/run.sh" > Procfile'
- mv node_modules/ep_etherpad-lite/node_modules/ep_* node_modules
- cp -R node_modules/ep_etherpad-lite/node_modules/log4js node_modules/
- rm node_modules/ep_etherpad-lite
- 'rm src/package.json && mv src/package-no-plugin.json src/package.json'
- npm install || npm install
- sed -i 's/npm install --loglevel warn//g' bin/installDeps.sh
- sed -i -e 's/ENGINE=MyISAM/ENGINE=INNODB/' src/node_modules/ueberdb2/mysql_db.js
- zip -r etherpad-lite-cf ./*
deploy:
  provider: releases
  api_key:
    secure: GDExihYPG0uY9ZmrA1uGYXwQiQ39Y5qbrP472b7DJ6lWrGPI1+CN1l+aFDs9dn6yQbmHt+0z/epBOCCMIAQ/LUofULzSPhAWaoi0sEOzX/xF2jAYULdOJq9cpEjfQkEI+D1xsfkxY8HMe05Wxaj/S0Wd9X+zAQbMiPfFktkUv00=
  file: etherpad-lite-cf.zip
  on:
    tags: true
    all_branches: true
